### PR TITLE
Adding ability to place shadow under slider thumbs

### PR DESCRIPTION
**Pull request by justincpollard**
I added the facility to create a drop shadow under the thumb sliders using a `Path`, x- and y- offsets, and a blur radius.

### CODE REVIEW

**Comment by dbachelder** [comment]
@anothem have you had a chance to review this?

**Comment by dbachelder** [comment]
@justincpollard looks like this will need a rebase

**Comment by anothem** [comment]
@justincpollard I apologise for the delay. When I first looked at it I wasn't sure if this is a good customisation to have for everyone, or if it just serves a very specific need, so I decided I'll think about it some more and then it just slipped my mind. I'll get back to you in a few days max and don't worry about the merge conflicts, I'll sort them out myself if we merge (they're mostly caused by the package name change).

**Comment by justincpollard** [comment]
Thanks, @anothem! I understand your concern. To give you a brief rational, the ability for us to add shadow to our slider thumbs helps us customize the slider to fit our brand while also holding on to a bit of Material Design flare: namely shadows caused by elevation of the thumbs.

**Comment by anothem** [comment]
I have looked at this more closely over the weekend. I think the ability to add shadows to this is quite cool, we should definitely get something like that in. Shadows probably should be default on Lollipop and after as well, but we can do that in a later PR. 

I'm just a bit concerned with what the shadow actually looks like. It's more like a glow than [material shadows](https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-). 

Not entirely sure why that is, might have to do with how the blurring. I'd be glad to dig into it and see if I can improve, but wondering if you have any suggestions or thoughts?

**Comment by justincpollard** [comment]
Hey @anothem I think one of the differences between the shadow we're drawing on the slider thumbs and the shadow drawn by `android:elevation` is the color. Here's an example in our app:

**slider thumb**
_approximate rgb: 230, 230, 230_
device-2015-08-24-095910

**FAB with 6dp elevation**
_approximate rgb: 195, 195, 195_
device-2015-08-24-100214

Maybe using a darker default color would make the shadow like more Material-ish? Since I added an attr to allow for specifying the shadow color, changing the default isn't a huge deal.

**Comment by anothem** [comment]
Good point! So here's my suggestion then, if you agree with it. 
If you just set thumbShadow=true and nothing else, we should come up with a default that looks decently material. So the offsets shouldn't default to zero, for example. This way, most users will probably just use that and if anyone needs something more specific, they can use the extra attributes to configure.

**Comment by justincpollard** [comment]
@anothem just updated my fork. Check out the sample project to see the defaults; let me know what you think!

**Comment by anothem** [comment]
Yeah, much better defaults! Thanks!

**Comment by anothem** [comment]
I've created a branch, "shadows-wip" for this: https://github.com/anothem/android-range-seek-bar/tree/shadows-wip
You should be able to merge this change against that branch without a problem. Please edit the pull request to be against the new branch and I'll merge it. The branch itself will be merged in master shortly after, just need to do the merging and figure out any last remaining issues.

**Comment by justincpollard** [comment]
@anothem done!

**Pull request closed without merging**
